### ISSUE TITLE
docker-zh-mac版

### ISSUE THREAD

**Issue by fffhk** [tangyabo/Docker-Desktop-ZH#1]
docker-zh-mac版
您好，请问你的mac中文汉化版什么时候可以好啊！

**Comment by tangyabo** [comment]
下周吧，这段时间比较忙，弄了一半了，也是只支持4.28版本，目前最新版本做汉化的时候有未知的问题。

**Comment by fffhk** [comment]
亲，我為什麼找不到app.asar這個文件，按你的路徑
